### ISSUE TITLE
TestReport: Hypoventilation Alarm

### ISSUE THREAD

**Issue by CohenLabPrinceton** [CohenLabPrinceton/pvp#109]
- [ ] a. VSE must monitor and alarm for hypoventilation

- [ ] b. Alarm OFF is allowable here

- [ ] c. NOTE The hypoventilation ALARM CONDITION can be determined, inter alia, by the measurement of the variations of AIRWAY PRESSURE, or expired volume, but possibly needs additional detection means. The hypoventilation ALARM CONDITION can also be determined by an INTELLIGENT ALARM SYSTEM utilizing one or more variables.

**Comment by CohenLabPrinceton** [comment]
@mschottdorf @zajdel @sneakers-the-rat We need to describe how we do this.

**Comment by sneakers-the-rat** [comment]
VTE can now set High/low VTE alarm by recording recent values, just need to know what i should use as the alarm threshold (eg. +/- 10% of set value like PIP, etc.)
https://github.com/CohenLabPrinceton/Ventilator-Dev/commit/88faef7bc1e5bf982c6abc3a2d71313329c64d1f
