### ISSUE TITLE
TestReport: High Leakage Alarm

### ISSUE THREAD

**Issue by CohenLabPrinceton** [CohenLabPrinceton/pvp#110]
- [ ] a) The VENTILATORY SUPPORT EQUIPMENT may be equipped with an ALARM SYSTEM that detects a TECHNICALALARM CONDITION to indicate when conditions in the VBS reach the ALARM LIMIT for high leakage.

- [ ] b) If provided, the high leakage TECHNICAL ALARM CONDITION shall be at least MEDIUM PRIORITY, unless an INTELLIGENT ALARM SYSTEM, based on additional information, determines that the high leakage TECHNICAL ALARM CONDITION is suppressed, or its priority is changed

**Comment by CohenLabPrinceton** [comment]
@mschottdorf @sneakers-the-rat need to confirm leakage alarm exists and works.

**Comment by sneakers-the-rat** [comment]
Tell me how to parameterize leak and i'll implement in alarm manager.

**Comment by CohenLabPrinceton** [comment]
@mschottdorf @zajdel we need to think about how the controller knows when there is a leak. Normally that would be handled by mass conservation with dual flow sensors, but we need an alternative. Might be issues with rise time, or maintaining pressure, etc.
