### ISSUE TITLE
TestReport: Prevention of accidental changes

### ISSUE THREAD

**Issue by CohenLabPrinceton** [CohenLabPrinceton/pvp#112]
Protection against accidental adjustments

- [x] a) Means of protection against accidental adjustment of controls that can create a HAZARDOUS SITUATION

shall be provided, including at least the following.

- [x] 1) Switching on the VENTILATORY SUPPORT EQUIPMENT and starting the ventilation shall require two different actions.

- [x] 2) It shall be possible to set all VENTILATORY SUPPORT EQUIPMENT parameters prior to starting

- [x] 3) Turning off the ventilation shall require at least a sequence of two very deliberate actions.

- [x] 4) Turning the VENTILATORY SUPPORT EQUIPMENT off shall require two different actions.

- [x] 5) Setting the MAXIMUM WORKING PRESSURE greater than 40 hPa shall require at least a sequence of two very deliberate actions.

- [x] b) These means may be accomplished by

1) utilizing hardware or software or a combination of both, or
2) two or more dedicated confirmation actions.
c) The USABILITY of these means of protection shall be evaluated in the USABILITY ENGINEERING PROCESS

**Comment by CohenLabPrinceton** [comment]
@sneakers-the-rat @zajdel @juliennelachance big one on basic safety. I think our regulators, etc. are difficult to change accidentally. Our software controls include multiple confirmations, etc. Let's formally confirm these please by answering these check boxes.

**Comment by CohenLabPrinceton** [comment]
@sneakers-the-rat please check off the boxes here.

**Comment by sneakers-the-rat** [comment]
need to implement lock mode, on my life

**Comment by sneakers-the-rat** [comment]
lock mode implemented

**Comment by sneakers-the-rat** [comment]
5) is here: https://github.com/CohenLabPrinceton/Ventilator-Dev/commit/67745423707d28f3d8b9238433542be21451ac37

**Comment by sneakers-the-rat** [comment]
what's the difference between (3) and (4)?

**Comment by sneakers-the-rat** [comment]
ventilator can be turned off with two deliberate actions - pressing STOP and then pressing "OK" in dialog box that asks user to confirm stopping ventilation and warns that doing so prematurely is dangerous. if 3 and 4 are equivalent this is finished:

https://github.com/CohenLabPrinceton/Ventilator-Dev/commit/9302c9f0ef627b171b291b6ab04d4a5a42924289

**Comment by sneakers-the-rat** [comment]
closing this unless there's further comment
