### ISSUE TITLE
Independence of ventilation control and risk control

### ISSUE THREAD

**Issue by CohenLabPrinceton** [CohenLabPrinceton/pvp#114]
a) A SINGLE FAULT CONDITION shall not cause the simultaneous failure of:

- [ ] 1) the ventilation‐control function; and

- [ ] 2) the corresponding PROTECTION DEVICE.

b) A SINGLE FAULT CONDITION shall not cause failure in such a way that a failure of:

- [ ] 1) the ventilation‐control function and the corresponding MONITORING EQUIPMENT is not detected,
or

- [ ] 2) the ventilation‐control function and the corresponding ALARM SYSTEM is not detected

**Comment by sneakers-the-rat** [comment]
need to know what 
* SINGLE FAULT CONDITION, 
* 'ventilation-control function', 
* 'PROTECTION DEVICE', and 
* 'MONITORING EQUIPMENT' 
mean to answer this
