### ISSUE TITLE
TestReport: Programmable Electrical Medical Systems (PEMS)

### ISSUE THREAD

**Issue by CohenLabPrinceton** [CohenLabPrinceton/pvp#115]
- [ ] Indicate whether the software was developed under a controlled life cycle process (e.g. IEC 62304 Medical device software — Software life cycle processes).   List any known unresolved software anomalies and workarounds.

**Comment by CohenLabPrinceton** [comment]
We don't need to use 62304, but we should discuss this fairly.

**Comment by sneakers-the-rat** [comment]
not sure what's required here, unfamiliar with 'controlled life cycle processes.' if this could get juiced out into specific questions i can answer them. seems like 'how did we go about planning development?'

**Comment by mschottdorf** [comment]
- Current software-anomaly: glitches from the hardware sensors.
