### ISSUE TITLE
Optimizing PID control coefficients and performance

### ISSUE THREAD

**Issue by mschottdorf** [CohenLabPrinceton/pvp#123]
This is to track progress on the dinky, and find the optimal settings to control hardware.

**Comment by zajdel** [comment]
Main concern right now is that setting the pressure upstream of the prop valve may not be giving us a high enough flow rate to inflate the lung within 0.2-0.3 seconds, regardless of PIP setting.

**Comment by CohenLabPrinceton** [comment]
@mschottdorf @zajdel can you put some waveforms up? Does this depend at all on the inspiratory time setting?

**Comment by zajdel** [comment]
Significant progress achieved by using gain scheduling to account for the delay in the pressure propagation. Committed, but not pushed yet. I think I just need to be given push access to manuel's fork.

**Comment by zajdel** [comment]
![image](https://user-images.githubusercontent.com/28608975/85567905-3e04a080-b5ff-11ea-9cda-eaa8caf6de7f.png)

Showing results from test condition 4 (compliance: 20, resistance: 20, PIP: 35, PEEP: 10)

**Comment by mschottdorf** [comment]
I'll implement djc's matlab export, fix J's issues with the PR, then merge your stuff, and we are good :-)

**Comment by mschottdorf** [comment]
also done!
