### ISSUE TITLE
Flow: Fix the GUI, fix the calibration

### ISSUE THREAD

**Issue by CohenLabPrinceton** [CohenLabPrinceton/pvp#126]
- [ ] Tidal Volumes calculation and display needs to be correct

- [x] LPM not LPS for flow

- [ ] @juliennelachance will follow up with @SophieDvali 

- [ ] Revised interface

**Comment by sneakers-the-rat** [comment]
what does 'revised interface' mean?

**Comment by sneakers-the-rat** [comment]
displayed units are now correct (L/min rather than l/s) https://github.com/CohenLabPrinceton/Ventilator-Dev/pull/127/commits/55a48cf19c2679f4548f0144dd8e34a08bfeac3b#
