### ISSUE TITLE
Remove all traces of PEEP_TIME

### ISSUE THREAD

**Issue by sneakers-the-rat** [CohenLabPrinceton/pvp#130]
I'm removing the PEEPt setting from the GUI now, but it looks like it's still used elsewhere in the code. Want to make sure the removal is safe & there aren't any side effects of it hanging around in the code.

If i'm way off and y'all have come up with some better solution then my b go ahead and close this.

I can handle the trivial ones in the gui and `vent.common.values` but I need some advice from @mschottdorf on these:

https://github.com/CohenLabPrinceton/Ventilator-Dev/blob/5cabd7b9ae1601d0fc740600fbe4ac825d1a0145/vent/controller/control_module.py#L79

https://github.com/CohenLabPrinceton/Ventilator-Dev/blob/5cabd7b9ae1601d0fc740600fbe4ac825d1a0145/vent/controller/control_module.py#L92

https://github.com/CohenLabPrinceton/Ventilator-Dev/blob/5cabd7b9ae1601d0fc740600fbe4ac825d1a0145/vent/controller/control_module.py#L183

https://github.com/CohenLabPrinceton/Ventilator-Dev/blob/5cabd7b9ae1601d0fc740600fbe4ac825d1a0145/vent/controller/control_module.py#L201

https://github.com/CohenLabPrinceton/Ventilator-Dev/blob/5cabd7b9ae1601d0fc740600fbe4ac825d1a0145/vent/controller/control_module.py#L213

https://github.com/CohenLabPrinceton/Ventilator-Dev/blob/5cabd7b9ae1601d0fc740600fbe4ac825d1a0145/vent/controller/control_module.py#L533

https://github.com/CohenLabPrinceton/Ventilator-Dev/blob/5cabd7b9ae1601d0fc740600fbe4ac825d1a0145/vent/controller/control_module.py#L542

https://github.com/CohenLabPrinceton/Ventilator-Dev/blob/5cabd7b9ae1601d0fc740600fbe4ac825d1a0145/vent/controller/control_module.py#L553

https://github.com/CohenLabPrinceton/Ventilator-Dev/blob/5cabd7b9ae1601d0fc740600fbe4ac825d1a0145/vent/controller/control_module.py#L313

https://github.com/CohenLabPrinceton/Ventilator-Dev/blob/5cabd7b9ae1601d0fc740600fbe4ac825d1a0145/vent/controller/control_module.py#L348

**Comment by mschottdorf** [comment]
all removed in the controller
