### ISSUE TITLE
List of good features

### ISSUE THREAD

**Issue by sneakers-the-rat** [CohenLabPrinceton/pvp#75]
Let's start braggin.  What do we do well? Comment i'll keep this list updated

## Software as a whole

1. Is super fast. No problems with PID and 10ms loop time. If we find the time, we should measure how fast we actually are.

2. Very limited load on the PI. With 10ms loop time, controlling the dinky through ssh w/o UI is ~25% CPU load and 5% memory.

## GUI

- ay we have one
- Modularly designed with widely-used open-source GUI framework (Qt, PySide2)
- etc. jonny will fill out

## Alarms

- Flexible but inspectable alarm declaration syntax
- etc. jonny will fill out

## Controller

1. We support two control schemes, PID and state control. These are very simple to adjust should the need arise, and particularly flexible for adjustment to specific needs. For example, if PEEP valves become unobtanium, the PID-loop can actively control PEEP.

2. The Controller is concise, modular, subject to a well-documented API, and fully open source. This makes it much easier to find, and fix, bugs.

3. Its modularity makes it easy to re-use the Controller with a different, or remote, UI.

4. Rigorous exception handling and careful time-outs make sure that the program as a whole remains operational.

**Comment by mschottdorf** [comment]
To the point of [PEEP valve] vs. [PID control of PEEP]. This works really well:

![image](https://user-images.githubusercontent.com/3635994/84055406-c5f17600-a982-11ea-8b73-bb8c5445c849.png)

Can be adjusted in the main controller loop with `PEEP_VALVE_SET = True`.
