### ISSUE TITLE
TestReport: Compliance with IEC 60601-1 sec. 5 for testing

### ISSUE THREAD

**Issue by ProfDJCohen** [CohenLabPrinceton/pvp#85]
This is a hard one. We need to certify to the best of our ability a variety of things about how testing is conducted. In some cases, we cannot do this (we do not have a synthetic 'finger' with a force sensor that we can use to test 'finger poking' resistance, for instance). 

We may also need to do a humidity test. I need eyes on this and feedback. 

We need serious advice on this. 
[IEC-60601-1-s5.pdf](https://github.com/CohenLabPrinceton/Ventilator-Dev/files/4723642/IEC-60601-1-s5.pdf)

**Comment by CohenLabPrinceton** [comment]
Need to talk to consultants about how to handle this? Say "not evaluated"?
