### ISSUE TITLE
TestReport: Testing Error Reporting

### ISSUE THREAD

**Issue by ProfDJCohen** [CohenLabPrinceton/pvp#87]
Ref: CR501 201.5.101.3

- [ ] Updated?

VENTILATORY SUPPORT EQUIPMENT testing errors
--

- [ ] a) For the purposes of this document, declared tolerances shall include the measurement uncertainty.

- [ ] b) The MANUFACTURER shall disclose the measurement uncertainty of each disclosed tolerance in the technical description.

**Comment by ProfDJCohen** [comment]
@zajdel @CommReteris @sneakers-the-rat @Sophie We need to make sure that we have a table of measurement uncertainty, etc. that we report in our labeling parameters and for every measured/derived parameter.

**Comment by sneakers-the-rat** [comment]
should the UI display static +/- % error tolerance message next to measured parameters?

**Comment by CohenLabPrinceton** [comment]
Nope. These need to go in the labeling documentation and disclosures in the manual, not the machine UI

**Comment by CohenLabPrinceton** [comment]
Update: @zajdel will test this using testing conditions for Pressure Control table from the ISO table. @SophieDvali can help fit the data if needed.

**Comment by SophieDvali** [comment]
I'm a little confused about the wording here, does this just mean we have to report the uncertainty of all measured quantities? Is this separate from the EUA items for reporting the error of the individual measured quantities?

**Comment by CohenLabPrinceton** [comment]
@SophieDvali these are the same things. We need to report the error for any quantities we show the user. I think if you have the error values for flow and volume then we should be good.

**Comment by sneakers-the-rat** [comment]
unassigning myself since this is a docs thing for the hardware team. lmk if you need help using the docs tho.
