### ISSUE TITLE
TestReport: Certification and Spec'ing of Single Use Parts

### ISSUE THREAD

**Issue by ProfDJCohen** [CohenLabPrinceton/pvp#89]
- [ ] a) if the VENTILATORY SUPPORT EQUIPMENT, its parts or ACCESSORIES are intended for single use,

information on characteristics and technical factors known to the MANUFACTURER that could pose a
RISK if the VENTILATORY SUPPORT EQUIPMENT, its parts or ACCESSORIES were reused.

b) if the VENTILATORY SUPPORT EQUIPMENT, its parts or ACCESSORIES are intended for single use,
information regarding:

- [ ] 1) the intended duration of use; and

- [ ] 2) the consequences for the PATIENT if use is beyond the specified duration of use.

**Comment by ProfDJCohen** [comment]
@julie @zajdel all of our disposable parts for single-use need spec-sheets and justifications for duration of use/issues if not complied with. This is really important for the documentation I think. We'll need a complete list of all EXTERNAL accessories, biocompatibility of these, and certification info.

**Comment by zajdel** [comment]
List of single-use parts:
- PEEP valve
- HMEF
- DAR filters
- Respiratory tubing

**Comment by CohenLabPrinceton** [comment]
@SophieDvali maybe can help get the spec sheets for these. 

Where does this go in the test report? Manual?
