### ISSUE TITLE
TestReport: Oxygen combustion safety

### ISSUE THREAD

**Issue by ProfDJCohen** [CohenLabPrinceton/pvp#93]
Ref: CR501 Clause 11 / IEC 60601-1 (11.2.2.1 is MISSING)

**RISK of fire in an OXYGEN RICH ENVIRONMENT**

If the medical device is intended to be used with oxygen:

- [ ] 	Describe means of protection to reduce the risk of ignition

If the medical device is intended to be used with oxygen operating at medical gas pipeline pressures:

- [x] Describe means of protection to taken to ensure that auto-ignition from adiabatic compression cannot occur

**Comment by ProfDJCohen** [comment]
AAMI CR502 implies that auto-ignition is only a risk at 5 bar or higher. 50 psig is 3.5 bar, so I think we're OK there. However, we need careful discussion of combustion risk mitigation.

**Comment by juliennelachance** [comment]
Ignition risk mitigation includes: no contactors (like relays: everything we're using is solid-state) so as to avoid arcs; enclosure of the electronics; avoiding aluminum in the oxygen pathway; etc.

**Comment by CohenLabPrinceton** [comment]
@juliennelachance thanks, but we need to be exhaustive, so please do not say ‘etc’. If there is something else that helps, write it explicitly. A concise, bulleted list is best.

**Comment by CohenLabPrinceton** [comment]
@zajdel speaker could be an issue.
