### ISSUE TITLE
TestReport: Accuracy of Controls and Visibility in the UI

### ISSUE THREAD

**Issue by CohenLabPrinceton** [CohenLabPrinceton/pvp#98]
@sneakers-the-rat @mschottdorf this is about exceeding safety limits and constraining selected output values:

Clause 12 – Accuracy of controls and instruments and protection against hazardous outputs
IEC 60601-1 is the guideline for all particular standards and, therefore, contain some requirements of a more general character in order to serve this purpose. For this reason, it is necessary to have some generally formulated requirements in Clause 12.
Standardization bodies, including those outside IEC, have adopted the system of this IEC publication in order to have a single uniform system of standards. In such cases it is most important to give a guideline in this clause.
This clause introduces the concept of USABILITY. The term was chosen over the commonly used terms of “user error” or “human error” because not all errors are the result of oversight or carelessness on the part of the OPERATOR of the ME EQUIPMENT. All too frequently, use errors are the direct result of poor human interface design that seduces the OPERATOR into an incorrect decision. Use errors caused by inadequate USABILITY have become an increasing cause for concern. The USABILITY ENGINEERING PROCESS described in IEC 60601-1-6 is intended to achieve reasonable USABILITY, which in turn is intended to minimise use errors and to minimise use associated RISKS.

- [x] Subclause 12.4.1 – Intentional exceeding of safety limits

If the control range of ME EQUIPMENT is such that the delivered output in a part of the range considerably differs from the output that is regarded as non-hazardous, means should be provided that prevent such a setting or that indicate to the OPERATOR (for example by means of an apparent additional resistance when the control is set or the bypassing of an interlock) that the selected setting is in excess of a safety limit.
Where appropriate, particular standards should specify safe output levels.

- [x] Subclause 12.4.3 – Accidental selection of excessive output values

Protection for the accidental selection of excessive output values can be obtained by appropriate steps to minimise the possibility to accidentally select excessive output, e.g. by interlocks in order to achieve deliberate action or by separated output terminals. In considering the measures for protection, the standard on human factors could be taken into account.

**Comment by CohenLabPrinceton** [comment]
@juliennelachance here because of screen discussion.

**Comment by CohenLabPrinceton** [comment]
nm, not required via AAMI update

**Comment by CohenLabPrinceton** [comment]
We need to agree on some quick bullet point responses to this here, I think.

**Comment by sneakers-the-rat** [comment]
I have a battery pack, but would be useful to have the battery pack that we plan on using for the final thing so i can test code that checks on power source

**Comment by sneakers-the-rat** [comment]
prompting for unsafe values implemented here: https://github.com/CohenLabPrinceton/Ventilator-Dev/commit/eccf78b56d75e1a997ce4f932677dab76ad6e7d0

- each controlled value has a `safe_range` .
- if the user attempts to set a value outside of the `safe_range`, they are prompted with a message like this:

<img width="538" alt="Screenshot 2020-06-22 14 40 19" src="https://user-images.githubusercontent.com/12961499/85337948-51482c80-b496-11ea-9bd7-cce24a05ad70.png">

- if the user presses 'ok,' the value is set and the user is not prompted until the value returns to & exits the safe range again.
- if the user presses 'cancel,' the value is set to the most recent value.

**Comment by sneakers-the-rat** [comment]
locking impemented: https://github.com/CohenLabPrinceton/Ventilator-Dev/commit/f93c78bc3ba32311b79aa461a9304ae8db18e3ca

before starting:
<img width="1680" alt="Screenshot 2020-06-22 16 19 30" src="https://user-images.githubusercontent.com/12961499/85344371-5a3ffa80-b4a4-11ea-819d-f250ff0a5325.png">

after starting, the ui starts in 'locked' mode by default, indicated by the green 'lock' icon and color-corresponding border around controls and the recession of the control subboxes into the main box background. While locked, none of the controls can be changed. 

<img width="1680" alt="Screenshot 2020-06-22 16 19 59" src="https://user-images.githubusercontent.com/12961499/85344420-7a6fb980-b4a4-11ea-8a53-1940e0ac209e.png">

The user can unlock the ui, allowing controls to be changed, by clicking the lock.

<img width="1680" alt="Screenshot 2020-06-22 16 20 15" src="https://user-images.githubusercontent.com/12961499/85344449-8e1b2000-b4a4-11ea-8ad2-50bae6b0efb8.png">
